"""Generate formatted reports from analysis results."""

from datetime import datetime
from typing import Dict
from analysis.framework import AnalysisResult


def generate_markdown_report(result: AnalysisResult, business_data: Dict) -> str:
    """Generate a markdown-formatted report."""
    
    report = f"""# Red Team Analysis Report
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Business Overview

**Name:** {business_data.get('name', 'N/A')}

**Target Market:** {business_data.get('target_market', 'N/A')}

**Revenue Model:** {business_data.get('revenue_model', 'N/A')}

---

## Analysis Results

### 1. THE VERDICT

**{result.verdict}**

{result.verdict_summary}

---

### 2. THE "KILL SHOT" (The Fatal Flaw)

{result.kill_shot}

---

### 3. SCENARIO SIMULATION (The Wargame)

#### Scenario A (The Market)
{result.scenario_market}

#### Scenario B (The Operations)
{result.scenario_operations}

#### Scenario C (The Black Swan)
{result.scenario_black_swan}

---

### 4. THE "STEEL MAN" ARGUMENT

{result.steel_man}

---

*This analysis was generated by The Devil's Advocate - Red Team Business Analyzer*
"""
    
    return report


def generate_text_summary(result: AnalysisResult) -> str:
    """Generate a brief text summary of the analysis."""
    
    summary = f"""
VERDICT: {result.verdict}

{result.verdict_summary[:200]}...

FATAL FLAW: {result.kill_shot[:150]}...
"""
    
    return summary.strip()


